Several bugs fixed

diff --git a/ansible/roles/backup_docker_control/files/bin/stop_docker b/ansible/roles/backup_docker_control/files/bin/stop_docker
--- a/ansible/roles/backup_docker_control/files/bin/stop_docker
+++ b/ansible/roles/backup_docker_control/files/bin/stop_docker
@@ -12,10 +12,12 @@ log_logging_application="BACKUP"
 
 [ $EUID -eq 0 ] || log_fatal  88 "Root privileges reqiured" 
 
-log_info "Stopping docker service"
-if systemctl stop docker
+
+
+log_info "Stopping docker.socker service"
+if systemctl stop docker.socket
 then
     log_info "Docker service stopped"
 else
-    log_fatal $? "Failed to stop docker service"
+    log_fatal $? "Failed to stop docker.socket service"
 fi
